name: Ejecutar monitoreo

on:
  schedule:
    - cron: "*/10 20-21 * * *"  # 22:00–23:59 (España)
    - cron: "*/10 22-23 * * *"  # 00:00–01:59
    - cron: "*/10 0-2 * * *"    # 02:00–04:59
    - cron: "*/10 3 * * *"      # 05:00–05:59
  workflow_dispatch:           # Permite ejecución manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          GRAFANA_SESSION: ${{ secrets.GRAFANA_SESSION }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python monitor_baterias.py
